apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-cronjob-view
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io