apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.postgres.storage.size }}
  hostPath:
    path: {{ .Values.postgres.storage.hostPath }}
  storageClassName: {{ .Values.postgres.storage.className }}