apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgres.database | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}