apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-legislators-processor
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: legislators-processor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    app: postgres
    role: service
spec:
  selector:
    app: postgres
    role: service
  type: {{ .Values.postgres.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      protocol: TCP
