apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    app: postgres
    role: service
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: postgres
      role: service
  serviceName: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: postgres
        role: service
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-postgres
          ports:
            - containerPort: {{ .Values.postgres.port }}
              name: postgres
              protocol: TCP
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres
