apiVersion: batch/v1
kind: CronJob
metadata:
  name: pyjob
  namespace: official-list
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pyjob
            image: travops87/officiallist:latest0
            command:
              - "python"
            args:
              - "/app/cron.py"
            env:
              - name: POSTGRES_DB
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: POSTGRES_DB
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: POSTGRES_USER
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: POSTGRES_PASSWORD
              - name: POSTGRES_HOST
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: POSTGRES_HOST
              - name: POSTGRES_PORT
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: POSTGRES_PORT
          restartPolicy: OnFailure
