apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: legislators-cronjob
  namespace: official-list
spec:
  schedule: "*/2 * * * *"  # Run every 2 minutes for testing
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: legislators-processor
            image: travops87/officiallist:latest  # Replace with your Python image
            command: ["/bin/sh", "-c"]
            args:
              - python /path/to/your/script.py
          restartPolicy: OnFailure