apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: official-list
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres
