apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
  namespace: official-list
spec:
  capacity:
    storage: 1Gi  # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/your/host/path"  # Replace with the host path on your Minikube host
